name: Nightly Develop Build

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *
  push:

env:
  DEBUG: true
  REF_CHECKOUT_BRANCH: develop
  RELEASE_NAME: Recent nightly build
  APPLICATION_PUBLISH_FOLDER: ./publish
  WINDOWS_ARTIFACT_NAME: WindowsBuildArtifact_x64
  RELEASE_ARTIFACT_FOLDER: artifacts

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    name: Check for changes in last 24 hours
    outputs:
      should-run: ${{ steps.should-run.outputs.should-run }}
    steps:
      - uses: actions/checkout@v3
        if: ${{ env.DEBUG == 'true' }}
      - uses: actions/checkout@v3
        if: ${{ env.DEBUG == 'false' }}
        with:
          ref: ${{ env.REF_CHECKOUT_BRANCH }}
      - name: get latest commit and check it
        id: should-run
        continue-on-error: true
        if: ${{ env.DEBUG == 'true' }} || ${{ github.event_name == 'schedule' }}
        # Based on https://stackoverflow.com/questions/63014786/how-to-schedule-a-github-actions-nightly-build-but-run-it-only-when-there-where
        run: |
          latest=$(git log -n 1 --pretty=format:"%H")
          sha=$(git rev-list --after="24 hours" $latest)
          echo $sha
          echo Do the check now
          if test -z $sha
          then
            echo "Check failed"
            echo "should-run=false" >> $GITHUB_OUTPUT
          else
            echo "Check successful"
            echo "should-run=true" >> $GITHUB_OUTPUT
          fi
  check-build:
    name: Check and Test build
    # Based on https://stackoverflow.com/questions/59882715/use-environment-variable-in-github-action-if
    if: needs.check-for-changes.outputs.should-run == 'true'
    needs: [check-for-changes]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.REF_CHECKOUT_BRANCH }}
        lfs: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  create-windows-build:
    name: Create Windows build
    if: ${{ needs.check-for-changes.outputs.should-run == 'true' }}
    needs: ["check-build"]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.REF_CHECKOUT_BRANCH }}
        lfs: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish Application
      run: dotnet publish -r win-x64 -c Release -o ${{ env.APPLICATION_PUBLISH_FOLDER }} --no-restore
    - name: Publish Application
      run: rm ${{ env.APPLICATION_PUBLISH_FOLDER }}\*.pdb
    - name: Show content for debug
      if: ${{ env.DEBUG == 'true' }}
      run: ls
    - name: Show content to publish
      if: ${{ env.DEBUG == 'true' }}
      run: |
        cd ./publish
        ls
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
       name: ${{ env.WINDOWS_ARTIFACT_NAME }}
       path: ${{ env.APPLICATION_PUBLISH_FOLDER }}
       if-no-files-found: error
  create-release:
    name: Create GitHub Release
    if: ${{ needs.check-for-changes.outputs.should-run == 'true' }}
    needs: ["create-windows-build"]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          path: ${{ env.RELEASE_ARTIFACT_FOLDER }}
      - name: Zip Windows build
        run: |
          cd ./$RELEASE_ARTIFACT_FOLDER/$WINDOWS_ARTIFACT_NAME
          zip -r $WINDOWS_ARTIFACT_NAME.zip ./*
          mv $WINDOWS_ARTIFACT_NAME.zip ../
      - name: display artifacts folder content
        if: ${{ env.DEBUG == 'true' }}
        run: ls -la $RELEASE_ARTIFACT_FOLDER
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_NAME }} [${{ GITHUB.RUN_NUMBER }}]
          tag: Develop-${{ GITHUB.RUN_NUMBER }}
          generateReleaseNotes: true
          body: Recent version of the develop branch, ready for testing
          draft: ${{ env.DEBUG }}
          prerelease: true
          artifacts: ${{ env.RELEASE_ARTIFACT_FOLDER }}/*.zip
          artifactContentType: "application/zip"